FROM golang:latest

RUN mkdir -p /app
WORKDIR /app

ADD . /app
RUN go get github.com/gin-gonic/gin
RUN go get github.com/auth0/go-jwt-middleware
RUN go get github.com/dgrijalva/jwt-go
RUN go build ./main.go

EXPOSE 3000

ENV GIN_MODE=release

CMD ["./main"]