FROM golang:latest

RUN mkdir -p /app
WORKDIR /app

ADD . /app
RUN go get github.com/gorilla/mux
RUN go get github.com/gorilla/handlers
RUN go get github.com/auth0-community/auth0
RUN go get github.com/satori/go.uuid
RUN go get github.com/auth0/go-jwt-middleware

RUN go build ./main.go

EXPOSE 8000

CMD ["./main"]